sudo: required

language: java

jdk:
- oraclejdk8

services:
- docker

before_deploy:
  - mvn -DskipTests package
  - export JAR_FILE=$(ls target/auth-*.jar)
  - echo "deploying $JAR_FILE to GitHub releases"

deploy:
  - provider: script
    script: mvn -DskipTests package -Ddocker.username=$DOCKER_USER -Ddocker.password=$DOCKER_PASS docker:build docker:push
    on:
      tags: true
  - provider: releases
    api_key:
      secure: WPEK5P558xqcCeH4i6ZP4IQTUYdpB96dzIskSR6qxlugnOEtvDKfrqj8vDCHvPvGGirzGsOnh+9cXWbFtzND6i3o5chzb9CYNNrV9qSJelpdj//PqUIQ99oioKwGQQjfgS76VBkEeyj/mUljgsUgUKkBM6r7xGISnaEHaq4vk4IPjKfZJoznLlk73Jo1tC+CqURwa1MiQSqJEO5WYt/fY4YJJW6jwfuXLv/K/6is3+nlSaxN4hlRFrnYXpmGdqrxh2q+QKW45gzBfFn+YtkzobMAPBbj7soofmF/lPS1Hhc5l2XXH90qHk0Dnppe5+kkiobN/SsdVRzm1eZ2xakZfojaz0WvLW3fhjBBiT1ZrmlFYMmoTy4hNScrQDOBlp+JhgOGmw2MkKtc1O+3t3l2r2X4Bdh2nkx1GlDfSZJSd3sV45LtDBL0RRzOwXiXv4s2u2y5VseOHWqb9/YmA5jcYQScNtejJBoMeYvC0KIPaHF2pbz7VwKjjEfUBRtFbcN6JFjgJcx6IUkcjzBJ9+LvE+c0wqE2ux+mrmiFJ7HIWWGd9TI/P4hb++r87jjkcJUe69l3KfisXNaA5ZCRM8x5NybWtu7ThNxMJACWVNYyOIsvEoHlhBWsZB/hBT9co3IZNLSAyB3GwtYk4AM3/3znTwO/P5cU8wLAbiPoVSiwP5w=
    file: "${JAR_FILE}"
    skip_cleanup: true
    on:
      tags: true
      repo: coffeenet/coffeenet-auth

env:
  global:
  - secure: kZR6Pvt+oNwghw5B6BBdbT5M1FgOd0R+OzGTjTnTE7JY3xi1HnmpVj3q9TGdKvwVcAOkfH2rRVKob3CO7PcuI/wTp2YJfxQcpboIQATPG4ICji3BHvy56E6VkWFdbuJgNTEHzjnAFddNzenfteTDsmEu/MJcTUXLSf56cR7j8vfNKY7frdDZxr2f5pLIxjI7G9CmfBwifhxeiCnYvGvZ12oKCzEKotHMIuGcN4iek3bWZ+7ANXSNZV+5nPFTgFuv1x/3vvKMsLjPMybt9SBINH419NiAuamKJc5t5h5VbBUs+YyQW3nNzEuQqjqLfC9Zz0L72oO4uSu6wxV/QOKGlrSnqA0RHZoYbPRe/iYwUt/D6XfEYS+Rm3s2cVEkhhJT8cU6pKDDVRzWows/LChkFGqXrdZuQVKol8kwNVZOP7358I3nsDAyVyT8wOOD4Xm8cyounIePWkqgcHAmNqaUN7B4dWApPxczVAs/uZP4Ap7hXDWcRJSBCJcFpzef1/ZGNwUvkHdJfmT3MHbC33snCV4m4MM6R8UsUlkeL7jqDuyzR5TIpPsHdzOJHuQhlC8zn4FqhJJbvuILzCGDo5K+yqwm1giuVX21t7k0CMbS9ZH7GtLiX0U2yWpV918CJ7xb0yHjD+86HsoRXtMzKOrh+RvbZsodK89ohV2gRiACJvo=
  - secure: irn/WxIPc7JFhiV//lbvmvB4NArobcNo1PUjNur85IMeSn625nWR3gs9VdtFPsUBM+8vMaehPRAkXH/E9Ozicyju2qXe37NeUnvCknsVFpAmVY05xJSKn3h3dCYPiPeSyTmSEtdNCTdOmEVXUDmPun4IXksi3cia+36fTBFeJmflM+rfowZQEwMBTMimjF4/Lr8PyovbUqCiMBrHqhhClSRLeSWM3OgC93PtYubm0FmntcM5DoZn6qtDhuIvKyJDpuGcufC7zp/7n3FQc22Nw7O9rIXwCAGBeV+WnGZ+sOOD9jzCwmuqolIk5XYUmVZoHtDP9w+i8eohN36Yh9UvGeeeOCErocGtTI9ekd28qYSGDRdaK4UXq2wFSB0+wH6V3KeoIjD0JAYaj1GN+JKfU59OkWzoF4SkrfqZJ5R+yTp071yOYbRy9kkpDwoRMlyeR1xvEy90uAth0QHYU6+BmwQBBE2hbHh2TqB9S39ApaijweJYc9qtuZDbioBkyGgVSSbZvHmV7HMJeBD98ma/U0eM3Yod++Np1JKTfH2tmpwD3aOeLkIVmNnGLLquPmvg7Y2REEx17mQGX3OsBE3ipvQM900cplECUXzrdxLLtFZN9Ej/ecx80w1Fd3AYCGtO+RhVZMA79jj5/FipuVl6LcRE04Pnag4m9ahsQBtt3w8=