coffeenet:
  profile: development
  application-name: CoffeeNet Auth
  allowed-authorities: ROLE_COFFEENET-ADMIN
  security:
    enabled: false
  discovery:
    instance:
      home-page-url: http://localhost:9999/clients
  logging:
    console:
      enabled: true

auth:
  development: true
  ldap:
    url: ldap://localhost:38900
    base: dc=coffeenet
    userSearchBase: ou=People
    userSearchFilter: uid={0}
    groupSearchBase: ou=Groups
    groupSearchFilter: member={0}
    connection-with-tls: false
    bindDn:
    bindPassword:
  token:
    access-token-validity-seconds: 3600
    refresh-token-validity-seconds: 43200

server:
  port: 9999
  session:
    cookie:
      name: coffee-cookie

spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/auth
    username: auth
    password: auth
    driver-class-name: org.mariadb.jdbc.Driver
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  messages:
    fallback-to-system-locale: false
