server:
  port: ${PORT:8761}

eureka:
  client:
    service-url:
      defaultZone: http://coffeenet-discovery.synyx.coffee:8761/eureka/
    registerWithEureka: true
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: coffeenet-discovery.synyx.coffee
    non-secure-port: 8761
    metadata-map:
      allowedAuthorities: ROLE_COFFEENET-ADMIN

spring:
  application:
    name: CoffeeNet Discovery